<a href="https://colab.research.google.com/github/shrikrishnachannawar/Basics_of_pytorch-/blob/main/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch fundamentals

* Resource Notebook:https://www.learnpytorch.io/

In [1]:
import torch

In [2]:
print(torch.__version__)

2.0.1+cu118


## Random tensors

Why random tensor?

Random tensors are import because the many
neural network learn is that start with tensors full of random number and then adjust those random numbers to better represent the data.

`Start with  random number -> Update random numbers-> look at the data->update random numbers`

Torch random tensors:https://pytorch.org/docs/stable/generated/torch.rand.html

In [3]:
#create the random tensor of size(3,4)
random_tensor =torch.rand(3,4)
random_tensor

tensor([[0.4291, 0.9884, 0.3457, 0.4817],
        [0.9659, 0.5641, 0.1436, 0.1091],
        [0.4276, 0.8344, 0.1757, 0.1964]])

In [4]:
#create a random tensors with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(3,224,224))#hight,width,color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [5]:
zeros=torch.zeros(size=(2,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
ones=torch.ones(size=(4,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [7]:
#use of torch.range() and get deprecated massage use torch.arrage()
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
#create tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatype is one of the 3 big error you will run into with PyTorch and deep learning:

1. Tensors not roght datatype.
2. Tensors not right datatype.
3. Tensors not on the right device.

In [9]:
#float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None, #waht datatype is tensor
                             device=None, #what device is your tensor on
                             requires_grad=False)# weather or not to track gradiant with this tensor operations.
float_32_tensor

tensor([3., 6., 9.])

In [10]:
float_32_tensor.dtype

torch.float32

In [11]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [12]:
another_float=float_16_tensor*float_32_tensor
another_float.dtype, another_float

(torch.float32, tensor([ 9., 36., 81.]))

In [13]:
int_32_tensor=torch.tensor([3,6,7],dtype=torch.int64)
int_32_tensor

tensor([3, 6, 7])

In [14]:
int_32_tensor*another_float

tensor([ 27., 216., 567.])

### Getting information from tensor
1. Tensors not right datatype-to do get datatyp from tensor,can use `tensor.dtype`
2. Tensor not right shape-to get shape from a tensor can use `tensor.shape`.
3. Tensor not on the right device-to get device from a tensor,can use `tensor.device`.

In [15]:
#create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.5981, 0.0886, 0.3565, 0.7404],
        [0.0130, 0.1345, 0.6312, 0.1868],
        [0.1443, 0.5091, 0.1298, 0.0514]])

In [16]:
#find out detail about some tensor
print(some_tensor)
print(f"shape of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.size}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5981, 0.0886, 0.3565, 0.7404],
        [0.0130, 0.1345, 0.6312, 0.1868],
        [0.1443, 0.5091, 0.1298, 0.0514]])
shape of tensor: torch.float32
shape of tensor: <built-in method size of Tensor object at 0x784023c049f0>
Device tensor is on: cpu


### Manupilation of tensor (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication(elemet wise)
* Division
* Matrix Multiplication

In [17]:
#create a tensor
tensor=torch.tensor([5,6,7])
tensor


tensor([5, 6, 7])

In [18]:
tensor + 10

tensor([15, 16, 17])

In [19]:
tensor*10

tensor([50, 60, 70])

In [20]:
tensor-9

tensor([-4, -3, -2])

In [21]:
#py-torch inbuilt function
torch.mul(tensor,10)

tensor([50, 60, 70])

In [22]:
torch.add(tensor,5)

tensor([10, 11, 12])

### Matrix multiplication
Two main ways of performing multiplication in neural network and deep learning:

1. Element-wise multiplication
2. Matrix-multiplication


There are two main rule that perforrming matrix multiplication need to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)`wont  work
* `(3,2) @ (2,3) and wise versa` won't work
2. The resulting matrix has  the shape of the **Outer dimension**:
* `(2,3)@(3,2)->(2,2)`


In [23]:
# element-wise multiplication
print(tensor,"*",tensor)
print(tensor*tensor)

tensor([5, 6, 7]) * tensor([5, 6, 7])
tensor([25, 36, 49])


In [24]:
#matrix multiplcation
torch.matmul(tensor,tensor)

tensor(110)

**note:**The pytorch opeartor is so much faster than simple operator.

In [25]:
%%time
value=0
for i in range(len(tensor)):
  value +=tensor[i]*tensor[i]
print(value)


tensor(110)
CPU times: user 1.58 ms, sys: 0 ns, total: 1.58 ms
Wall time: 1.59 ms


In [26]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 63 µs, sys: 14 µs, total: 77 µs
Wall time: 80.6 µs


tensor(110)

In [27]:
mat=torch.rand(size=(3,2))
mat1=torch.rand(size=(2,3))
mat,mat1

(tensor([[0.7796, 0.9138],
         [0.2124, 0.0090],
         [0.4995, 0.3964]]),
 tensor([[4.6229e-04, 9.0641e-01, 9.8462e-01],
         [8.5619e-01, 2.0472e-01, 2.9288e-02]]))

In [28]:
torch.matmul(mat,mat1)

tensor([[0.7827, 0.8937, 0.7944],
        [0.0078, 0.1944, 0.2094],
        [0.3396, 0.5339, 0.5034]])

### One of the Most common error in deep learning:shape error

In [30]:
# Shape for matrix multiplication
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])


tensor_B=torch.tensor([[7,8],
                       [8,9],
                       [10,11]])
#torch.mm(tensor_A,tensor_B)# torch.mm is the same as torch.matmul
torch.mm(tensor_A,tensor_B)



RuntimeError: ignored

**note:**To fox tensor issues,we can manipulate the shape of one of our tensor using a **transpos**.

In [31]:
tensor_A.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [32]:
print(f"Original shape:tensor_A= {tensor_A.shape},tensor_B={tensor_B}")
print(f"New shape:Tensor_A={tensor_A.shape} (same shape as above),tensor_B.T{tensor_B.T}")
print(f"Multiplying:{tensor_A.shape} @ {tensor_B.T.shape}<-inner dimensions must match")
print(f"output:\n")
output=torch.mm(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape:{output.shape}")


Original shape:tensor_A= torch.Size([3, 2]),tensor_B=tensor([[ 7,  8],
        [ 8,  9],
        [10, 11]])
New shape:Tensor_A=torch.Size([3, 2]) (same shape as above),tensor_B.Ttensor([[ 7,  8, 10],
        [ 8,  9, 11]])
Multiplying:torch.Size([3, 2]) @ torch.Size([2, 3])<-inner dimensions must match
output:

tensor([[ 23,  26,  32],
        [ 53,  60,  74],
        [ 83,  94, 116]])

Output shape:torch.Size([3, 3])


### Finding the min, max, mean,etc (tensor aggriation)

In [33]:
#create a tensor
x=torch.arange(1,100,10)
x,x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [34]:
#find the min
torch.min(x),x.min()

(tensor(1), tensor(1))

In [35]:
#find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [36]:
#find the mean
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [37]:
#find the sum
torch.sum(x),x.sum()

(tensor(460), tensor(460))

### finding the position min and max

In [38]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [39]:
#find the poistion in tensor that has the has the min value in argmin ()->rerturn thr index of min value inn tthe array
x.argmin()

tensor(0)

In [40]:
x[0]

tensor(1)

In [41]:
x.argmax()

tensor(9)

In [42]:
x[9]

tensor(91)

## Reshaping , stacking, squeezing and unsqueezing tensor

* Reshaping - Reshape an input tensor to a define shape.
* view - Return a view of an input tensor of certain shape but keep the same memory as the orginal tensor
* Stacking- combine multiple tensor on top of each other (vstack) or slide by slide (hstack)  
* Squeeze -  remove all `1` dimensions from tensor
* Unsqueeze - add a `1` dimensions ot a target tensor
* permute - Return a view of the input with dimensions permuted(swapped) in certain way.

In [43]:
x=torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [44]:
#applying the reshaping
x_reshaped1 =x.reshape(1,9)
x_reshaped1, x_reshaped1.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [45]:
x_reshaped =x.reshape(3,3)#the mutiplication of size should be equal to the shape
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [46]:
#change the view
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [47]:
#Changing z changes x (because a view of tensor shares the same memory as the original input)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [48]:
#stack tensors on top each other
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [49]:
#squeezing the tensor
zeros=torch.zeros(3,1,3,1,3)
zeros.size()

torch.Size([3, 1, 3, 1, 3])

In [50]:
zeros_s=torch.squeeze(zeros)
zeros_s.shape

torch.Size([3, 3, 3])

In [51]:
x_reshaped1.squeeze().shape

torch.Size([9])

In [52]:
#torch.squeeze()-removes all single dimensions from target from a target tensor
print(f"previous tensor:{x_reshaped1}")
print(f"pervious shape:{x_reshaped1.shape}")

#remove the extra dimensions from x_shaped
x_squeeze=x_reshaped1.squeeze()
print(f"\n new  tensor:{x_squeeze}")
print(f"new shape:{x_squeeze.shape}")


previous tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
pervious shape:torch.Size([1, 9])

 new  tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
new shape:torch.Size([9])


In [53]:
#torch.unsqueeze()-add all single dimensions from target from a target tensor
print(f"previous tensor:{x_squeeze}")
print(f"pervious shape:{x_squeeze.shape}")

#remove the extra dimensions from x_shaped
x_unsqueeze=x_squeeze.unsqueeze(dim=0)
print(f"\n new  tensor:{x_unsqueeze}")
print(f"new shape:{x_unsqueeze.shape}")

previous tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
pervious shape:torch.Size([9])

 new  tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new shape:torch.Size([1, 9])


In [56]:
# torch.permute - rearrange the dimensions of a target tensor in a specifies
x_original=torch.rand(size=(224, 224, 3))#hight width color_channels
x_original

tensor([[[0.5109, 0.1911, 0.9391],
         [0.9297, 0.6537, 0.2364],
         [0.4784, 0.6008, 0.0427],
         ...,
         [0.1317, 0.4218, 0.8252],
         [0.8822, 0.9892, 0.1647],
         [0.3056, 0.0749, 0.7846]],

        [[0.0262, 0.5062, 0.8274],
         [0.8787, 0.3611, 0.8780],
         [0.3028, 0.6644, 0.8100],
         ...,
         [0.2150, 0.1302, 0.6667],
         [0.1917, 0.6600, 0.1853],
         [0.0644, 0.0396, 0.6210]],

        [[0.1138, 0.3779, 0.2405],
         [0.1288, 0.8669, 0.0368],
         [0.6603, 0.0368, 0.4561],
         ...,
         [0.1376, 0.8155, 0.9901],
         [0.9239, 0.2713, 0.1054],
         [0.6003, 0.7852, 0.2776]],

        ...,

        [[0.3357, 0.9552, 0.9895],
         [0.4602, 0.0188, 0.9067],
         [0.2236, 0.8106, 0.3032],
         ...,
         [0.1634, 0.4605, 0.2887],
         [0.9812, 0.2287, 0.0087],
         [0.3755, 0.6743, 0.2504]],

        [[0.5362, 0.5970, 0.6963],
         [0.3829, 0.8901, 0.6333],
         [0.